// Auto-generated by: npm run db:generate
// Manually maintained until Supabase CLI is configured

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          full_name: string | null
          avatar_url: string | null
          company_name: string | null
          role: 'admin' | 'sales' | 'viewer'
        }
        Insert: {
          id: string
          created_at?: string
          updated_at?: string
          full_name?: string | null
          avatar_url?: string | null
          company_name?: string | null
          role?: 'admin' | 'sales' | 'viewer'
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          full_name?: string | null
          avatar_url?: string | null
          company_name?: string | null
          role?: 'admin' | 'sales' | 'viewer'
        }
        Relationships: []
      }
      contacts: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          user_id: string
          name: string
          email: string | null
          phone: string | null
          company: string | null
          website: string | null
          notes: string | null
          status: 'lead' | 'prospect' | 'customer' | 'churned'
          tags: string[]
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          user_id: string
          name: string
          email?: string | null
          phone?: string | null
          company?: string | null
          website?: string | null
          notes?: string | null
          status?: 'lead' | 'prospect' | 'customer' | 'churned'
          tags?: string[]
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          user_id?: string
          name?: string
          email?: string | null
          phone?: string | null
          company?: string | null
          website?: string | null
          notes?: string | null
          status?: 'lead' | 'prospect' | 'customer' | 'churned'
          tags?: string[]
        }
        Relationships: []
      }
      quotes: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          user_id: string
          contact_id: string | null
          title: string
          description: string | null
          status: 'draft' | 'sent' | 'accepted' | 'rejected' | 'expired'
          total_amount: number
          currency: string
          valid_until: string | null
          ai_generated: boolean
          ai_prompt: string | null
          line_items: LineItem[]
          notes: string | null
          quote_request_id: string | null
          generated_by_ai: boolean
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          user_id: string
          contact_id?: string | null
          title: string
          description?: string | null
          status?: 'draft' | 'sent' | 'accepted' | 'rejected' | 'expired'
          total_amount?: number
          currency?: string
          valid_until?: string | null
          ai_generated?: boolean
          ai_prompt?: string | null
          line_items?: LineItem[]
          notes?: string | null
          quote_request_id?: string | null
          generated_by_ai?: boolean
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          user_id?: string
          contact_id?: string | null
          title?: string
          description?: string | null
          status?: 'draft' | 'sent' | 'accepted' | 'rejected' | 'expired'
          total_amount?: number
          currency?: string
          valid_until?: string | null
          ai_generated?: boolean
          ai_prompt?: string | null
          line_items?: LineItem[]
          notes?: string | null
          quote_request_id?: string | null
          generated_by_ai?: boolean
        }
        Relationships: []
      }
      quote_requests: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          user_id: string | null
          client_name: string
          client_email: string | null
          client_phone: string | null
          client_company: string | null
          request_text: string
          status: 'pending' | 'reviewing' | 'approved' | 'sent' | 'rejected'
          rejection_reason: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          user_id?: string | null
          client_name: string
          client_email?: string | null
          client_phone?: string | null
          client_company?: string | null
          request_text: string
          status?: 'pending' | 'reviewing' | 'approved' | 'sent' | 'rejected'
          rejection_reason?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          user_id?: string | null
          client_name?: string
          client_email?: string | null
          client_phone?: string | null
          client_company?: string | null
          request_text?: string
          status?: 'pending' | 'reviewing' | 'approved' | 'sent' | 'rejected'
          rejection_reason?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      contact_status: 'lead' | 'prospect' | 'customer' | 'churned'
      quote_status: 'draft' | 'sent' | 'accepted' | 'rejected' | 'expired'
      user_role: 'admin' | 'sales' | 'viewer'
      request_status: 'pending' | 'reviewing' | 'approved' | 'sent' | 'rejected'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

export interface LineItem {
  id: string
  description: string
  quantity: number
  unit_price: number
  total: number
}
